### ISSUE TITLE
AWSRioEnv __init__ throws error when credentials are not returned from botocore

### ISSUE THREAD

**Issue by roarmstrong** [opendatacube/dea-proto#1]
There is no guarantee that `botocore` will return a credentials object when `boto3.Session.get_credentials()` is called.
see: https://github.com/boto/botocore/blob/ddc8d9acdb67598c5a15b3e56eec8ff023993e30/botocore/credentials.py#L1655

This can cause errors when `AWSRioEnv` is constructed with `None` as the credentials object.

**Comment by Kirill888** [comment]
@roarmstrong I have pushed an attempt at a fix to `stable`, basic idea is to retry up to 10 times with some sleep in between. Also added assert in `AWSRioEnv`, `setup_local_env` will raise `IOError` if credentials can not be loaded after 10 attempts.
